// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPOVOdDroy_g-HhnVT__ZcNlY4yfNdb7g',
    appId: '1:893322695095:web:your-web-app-id',
    messagingSenderId: '893322695095',
    projectId: 'albert-personal-app',
    authDomain: 'albert-personal-app.firebaseapp.com',
    storageBucket: 'albert-personal-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPOVOdDroy_g-HhnVT__ZcNlY4yfNdb7g',
    appId: '1:893322695095:android:f2b25167906132275f1832',
    messagingSenderId: '893322695095',
    projectId: 'albert-personal-app',
    storageBucket: 'albert-personal-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPOVOdDroy_g-HhnVT__ZcNlY4yfNdb7g',
    appId: '1:893322695095:ios:your-ios-app-id',
    messagingSenderId: '893322695095',
    projectId: 'albert-personal-app',
    storageBucket: 'albert-personal-app.firebasestorage.app',
    iosBundleId: 'com.example.albertInfinity',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPOVOdDroy_g-HhnVT__ZcNlY4yfNdb7g',
    appId: '1:893322695095:ios:your-ios-app-id',
    messagingSenderId: '893322695095',
    projectId: 'albert-personal-app',
    storageBucket: 'albert-personal-app.firebasestorage.app',
    iosBundleId: 'com.example.albertInfinity',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPOVOdDroy_g-HhnVT__ZcNlY4yfNdb7g',
    appId: '1:893322695095:web:your-web-app-id',
    messagingSenderId: '893322695095',
    projectId: 'albert-personal-app',
    authDomain: 'albert-personal-app.firebaseapp.com',
    storageBucket: 'albert-personal-app.firebasestorage.app',
  );
}
